import { z } from 'zod';
import { paginationQuerySchema } from '../../shared/utils/pagination.js';
import { buildOpenApiDocument, type RouteSpec } from './openapi.builder.js';

import { registerSchema, loginSchema, refreshSchema } from '../../modules/auth/auth.schema.js';
import { updateUserSchema } from '../../modules/users/users.schema.js';
import {
  createHouseholdSchema,
  householdIdParam as householdsIdParam,
  updateHouseholdSchema,
  memberParam,
  updateMemberRoleSchema,
} from '../../modules/households/households.schema.js';
import {
  householdIdParam as invitationsHouseholdIdParam,
  createInvitationSchema,
  invitationIdParam,
  tokenSchema,
} from '../../modules/invitations/invitations.schema.js';
import {
  householdIdParam as categoriesHouseholdIdParam,
  createCategorySchema,
  updateCategorySchema,
  categoryIdParam,
} from '../../modules/categories/categories.schema.js';
import {
  householdIdParam as expensesHouseholdIdParam,
  createExpenseSchema,
  updateExpenseSchema,
  expenseIdParam,
  listExpensesQuerySchema,
} from '../../modules/expenses/expenses.schema.js';
import {
  householdIdParam as settlementsHouseholdIdParam,
  settlementIdParam,
  createSettlementSchema,
  listSettlementsQuerySchema,
} from '../../modules/settlements/settlements.schema.js';
import {
  householdIdParam as incomesHouseholdIdParam,
  incomeIdParam,
  createIncomeSchema,
  updateIncomeSchema,
  listIncomesQuerySchema,
} from '../../modules/incomes/incomes.schema.js';
import {
  householdIdParam as transfersHouseholdIdParam,
  transferIdParam,
  createTransferSchema,
  listTransfersQuerySchema,
} from '../../modules/transfers/transfers.schema.js';
import {
  householdIdParam as recurringHouseholdIdParam,
  recurringExpenseIdParam,
  createRecurringExpenseSchema,
  updateRecurringExpenseSchema,
} from '../../modules/recurring-expenses/recurring-expenses.schema.js';
import {
  expenseIdParam as attachmentsExpenseIdParam,
  attachmentIdParam,
} from '../../modules/attachments/attachments.schema.js';
import { dateRangeSchema, overTimeSchema } from '../../modules/analytics/analytics.schema.js';

// activity and balances define their `{ params: { householdId } }` schema
// inline in their routes file rather than exporting it from a schema.ts —
// reconstructed here rather than exported solely for this doc's sake.
const householdIdOnly = { params: z.object({ householdId: z.string().uuid() }) };

/**
 * Declarative source of truth for the generated OpenAPI document: one entry
 * per route, reusing the exact Zod schemas each route already validates
 * against, so the spec can't drift from real request-validation behavior.
 */
const routes: RouteSpec[] = [
  // Auth
  {
    method: 'post',
    path: '/auth/register',
    tag: 'Auth',
    summary: 'Register a new user',
    auth: false,
    request: registerSchema,
    successStatus: 201,
    successDescription: 'User created; returns the user and a token pair',
  },
  {
    method: 'post',
    path: '/auth/login',
    tag: 'Auth',
    summary: 'Log in with email and password',
    auth: false,
    request: loginSchema,
    successStatus: 200,
    successDescription: 'Returns the user and a token pair',
  },
  {
    method: 'post',
    path: '/auth/refresh',
    tag: 'Auth',
    summary: 'Rotate a refresh token',
    auth: false,
    request: refreshSchema,
    successStatus: 200,
    successDescription: 'Returns a new token pair; the old refresh token is revoked',
  },
  {
    method: 'post',
    path: '/auth/logout',
    tag: 'Auth',
    summary: 'Revoke a refresh token',
    auth: false,
    request: refreshSchema,
    successStatus: 204,
    successDescription: 'Refresh token revoked',
  },
  {
    method: 'post',
    path: '/auth/logout-all',
    tag: 'Auth',
    summary: 'Revoke every session for the current user',
    successStatus: 204,
    successDescription: 'All refresh tokens for the user revoked',
  },

  // Users
  {
    method: 'get',
    path: '/users/me',
    tag: 'Users',
    summary: "Get the current user's profile",
    successStatus: 200,
    successDescription: 'Current user',
  },
  {
    method: 'patch',
    path: '/users/me',
    tag: 'Users',
    summary: "Update the current user's profile",
    request: updateUserSchema,
    successStatus: 200,
    successDescription: 'Updated user',
  },
  {
    method: 'get',
    path: '/users/me/invitations',
    tag: 'Users',
    summary: "List the current user's pending invitations (by email)",
    successStatus: 200,
    successDescription: 'Pending invitations',
  },

  // Households
  {
    method: 'post',
    path: '/households',
    tag: 'Households',
    summary: 'Create a household',
    request: createHouseholdSchema,
    successStatus: 201,
    successDescription: 'Household created; the creator becomes admin',
  },
  {
    method: 'get',
    path: '/households',
    tag: 'Households',
    summary: 'List the households the current user belongs to',
    successStatus: 200,
    successDescription: 'Households with the user’s role and member count',
  },
  {
    method: 'get',
    path: '/households/{householdId}',
    tag: 'Households',
    summary: 'Get household detail',
    request: householdsIdParam,
    successStatus: 200,
    successDescription: 'Household detail',
  },
  {
    method: 'patch',
    path: '/households/{householdId}',
    tag: 'Households',
    summary: 'Update a household',
    request: updateHouseholdSchema,
    successStatus: 200,
    successDescription: 'Updated household',
  },
  {
    method: 'delete',
    path: '/households/{householdId}',
    tag: 'Households',
    summary: 'Delete a household',
    request: householdsIdParam,
    successStatus: 204,
    successDescription: 'Household soft-deleted',
  },
  {
    method: 'get',
    path: '/households/{householdId}/members',
    tag: 'Households',
    summary: 'List active household members',
    request: householdsIdParam,
    successStatus: 200,
    successDescription: 'Active members',
  },
  {
    method: 'delete',
    path: '/households/{householdId}/members/{userId}',
    tag: 'Households',
    summary: 'Remove a household member',
    request: memberParam,
    successStatus: 204,
    successDescription: 'Member removed',
  },
  {
    method: 'patch',
    path: '/households/{householdId}/members/{userId}',
    tag: 'Households',
    summary: "Change a member's role",
    request: updateMemberRoleSchema,
    successStatus: 200,
    successDescription: 'Updated membership',
  },

  // Invitations
  {
    method: 'post',
    path: '/households/{householdId}/invitations',
    tag: 'Invitations',
    summary: 'Invite a user by email',
    request: createInvitationSchema,
    successStatus: 201,
    successDescription: 'Invitation created',
  },
  {
    method: 'get',
    path: '/households/{householdId}/invitations',
    tag: 'Invitations',
    summary: 'List household invitations (all statuses)',
    request: invitationsHouseholdIdParam,
    successStatus: 200,
    successDescription: 'Invitations',
  },
  {
    method: 'delete',
    path: '/households/{householdId}/invitations/{invitationId}',
    tag: 'Invitations',
    summary: 'Revoke a pending invitation',
    request: invitationIdParam,
    successStatus: 204,
    successDescription: 'Invitation revoked',
  },
  {
    method: 'post',
    path: '/invitations/{token}/accept',
    tag: 'Invitations',
    summary: 'Accept an invitation',
    request: tokenSchema,
    successStatus: 200,
    successDescription: 'Joined the household',
  },
  {
    method: 'post',
    path: '/invitations/{token}/reject',
    tag: 'Invitations',
    summary: 'Reject an invitation',
    request: tokenSchema,
    successStatus: 200,
    successDescription: 'Invitation rejected',
  },

  // Categories
  {
    method: 'get',
    path: '/categories',
    tag: 'Categories',
    summary: 'List the global category catalog',
    auth: false,
    successStatus: 200,
    successDescription: 'Global (system) categories',
  },
  {
    method: 'get',
    path: '/households/{householdId}/categories',
    tag: 'Categories',
    summary: 'List categories available to a household',
    request: categoriesHouseholdIdParam,
    successStatus: 200,
    successDescription: 'Global categories plus the household’s own',
  },
  {
    method: 'post',
    path: '/households/{householdId}/categories',
    tag: 'Categories',
    summary: 'Create a household category',
    request: createCategorySchema,
    successStatus: 201,
    successDescription: 'Category created',
  },
  {
    method: 'patch',
    path: '/households/{householdId}/categories/{categoryId}',
    tag: 'Categories',
    summary: 'Update a household category',
    request: updateCategorySchema,
    successStatus: 200,
    successDescription: 'Updated category',
  },
  {
    method: 'delete',
    path: '/households/{householdId}/categories/{categoryId}',
    tag: 'Categories',
    summary: 'Delete a household category',
    request: categoryIdParam,
    successStatus: 204,
    successDescription: 'Category soft-deleted',
  },

  // Expenses
  {
    method: 'post',
    path: '/households/{householdId}/expenses',
    tag: 'Expenses',
    summary: 'Create an expense with its splits',
    idempotent: true,
    request: createExpenseSchema,
    successStatus: 201,
    successDescription: 'Expense created',
  },
  {
    method: 'get',
    path: '/households/{householdId}/expenses',
    tag: 'Expenses',
    summary: 'List expenses',
    request: { params: expensesHouseholdIdParam.params, query: listExpensesQuerySchema },
    successStatus: 200,
    successDescription: 'Paginated expenses',
  },
  {
    method: 'get',
    path: '/households/{householdId}/expenses/{expenseId}',
    tag: 'Expenses',
    summary: 'Get expense detail',
    request: expenseIdParam,
    successStatus: 200,
    successDescription: 'Expense with its splits',
  },
  {
    method: 'patch',
    path: '/households/{householdId}/expenses/{expenseId}',
    tag: 'Expenses',
    summary: 'Update an expense',
    request: updateExpenseSchema,
    successStatus: 200,
    successDescription: 'Updated expense; splits recalculated if the amount changed',
  },
  {
    method: 'delete',
    path: '/households/{householdId}/expenses/{expenseId}',
    tag: 'Expenses',
    summary: 'Void an expense',
    request: expenseIdParam,
    successStatus: 204,
    successDescription: 'Expense voided',
  },
  {
    method: 'post',
    path: '/households/{householdId}/expenses/{expenseId}/confirm',
    tag: 'Expenses',
    summary: 'Confirm a pending recurring occurrence',
    request: expenseIdParam,
    successStatus: 200,
    successDescription: 'Occurrence confirmed, now active',
  },
  {
    method: 'post',
    path: '/households/{householdId}/expenses/{expenseId}/skip',
    tag: 'Expenses',
    summary: 'Skip a pending recurring occurrence',
    request: expenseIdParam,
    successStatus: 200,
    successDescription: 'Occurrence voided',
  },

  // Settlements
  {
    method: 'post',
    path: '/households/{householdId}/settlements',
    tag: 'Settlements',
    summary: 'Record a settlement between two members',
    idempotent: true,
    request: createSettlementSchema,
    successStatus: 201,
    successDescription: 'Settlement recorded',
  },
  {
    method: 'get',
    path: '/households/{householdId}/settlements',
    tag: 'Settlements',
    summary: 'List settlements',
    request: { params: settlementsHouseholdIdParam.params, query: listSettlementsQuerySchema },
    successStatus: 200,
    successDescription: 'Paginated settlements',
  },
  {
    method: 'delete',
    path: '/households/{householdId}/settlements/{settlementId}',
    tag: 'Settlements',
    summary: 'Void a settlement',
    request: settlementIdParam,
    successStatus: 204,
    successDescription: 'Settlement voided',
  },

  // Balances
  {
    method: 'get',
    path: '/households/{householdId}/balances',
    tag: 'Balances',
    summary: 'Get the net balance per member',
    request: householdIdOnly,
    successStatus: 200,
    successDescription: 'Derived balances, never stored',
  },
  {
    method: 'get',
    path: '/households/{householdId}/balances/simplified',
    tag: 'Balances',
    summary: 'Get the simplified debt graph',
    request: householdIdOnly,
    successStatus: 200,
    successDescription: 'Minimal set of who-pays-whom transfers',
  },

  // Incomes
  {
    method: 'post',
    path: '/households/{householdId}/incomes',
    tag: 'Incomes',
    summary: 'Record an income',
    idempotent: true,
    request: createIncomeSchema,
    successStatus: 201,
    successDescription: 'Income recorded (does not move balances)',
  },
  {
    method: 'get',
    path: '/households/{householdId}/incomes',
    tag: 'Incomes',
    summary: 'List incomes',
    request: { params: incomesHouseholdIdParam.params, query: listIncomesQuerySchema },
    successStatus: 200,
    successDescription: 'Paginated incomes',
  },
  {
    method: 'patch',
    path: '/households/{householdId}/incomes/{incomeId}',
    tag: 'Incomes',
    summary: 'Update an income',
    request: updateIncomeSchema,
    successStatus: 200,
    successDescription: 'Updated income',
  },
  {
    method: 'delete',
    path: '/households/{householdId}/incomes/{incomeId}',
    tag: 'Incomes',
    summary: 'Void an income',
    request: incomeIdParam,
    successStatus: 204,
    successDescription: 'Income voided',
  },

  // Transfers
  {
    method: 'post',
    path: '/households/{householdId}/transfers',
    tag: 'Transfers',
    summary: 'Record a transfer between two members',
    request: createTransferSchema,
    successStatus: 201,
    successDescription: 'Transfer recorded (does not move balances)',
  },
  {
    method: 'get',
    path: '/households/{householdId}/transfers',
    tag: 'Transfers',
    summary: 'List transfers',
    request: { params: transfersHouseholdIdParam.params, query: listTransfersQuerySchema },
    successStatus: 200,
    successDescription: 'Paginated transfers',
  },
  {
    method: 'delete',
    path: '/households/{householdId}/transfers/{transferId}',
    tag: 'Transfers',
    summary: 'Void a transfer',
    request: transferIdParam,
    successStatus: 204,
    successDescription: 'Transfer voided',
  },

  // Activity
  {
    method: 'get',
    path: '/households/{householdId}/activity',
    tag: 'Activity',
    summary: 'Get the unified activity feed',
    request: { params: householdIdOnly.params, query: paginationQuerySchema },
    successStatus: 200,
    successDescription: 'Chronological merge of expenses, incomes, transfers and settlements',
  },

  // Recurring expenses
  {
    method: 'post',
    path: '/households/{householdId}/recurring-expenses',
    tag: 'RecurringExpenses',
    summary: 'Define a recurring expense',
    request: createRecurringExpenseSchema,
    successStatus: 201,
    successDescription: 'Recurring expense defined',
  },
  {
    method: 'get',
    path: '/households/{householdId}/recurring-expenses',
    tag: 'RecurringExpenses',
    summary: 'List recurring expenses',
    request: recurringHouseholdIdParam,
    successStatus: 200,
    successDescription: 'Recurring expenses',
  },
  {
    method: 'get',
    path: '/households/{householdId}/recurring-expenses/upcoming',
    tag: 'RecurringExpenses',
    summary: 'List upcoming and overdue occurrences',
    request: recurringHouseholdIdParam,
    successStatus: 200,
    successDescription: 'Computed, not materialized until the job runs',
  },
  {
    method: 'patch',
    path: '/households/{householdId}/recurring-expenses/{recurringExpenseId}',
    tag: 'RecurringExpenses',
    summary: 'Update, activate or deactivate a recurring expense',
    request: updateRecurringExpenseSchema,
    successStatus: 200,
    successDescription: 'Updated recurring expense',
  },
  {
    method: 'delete',
    path: '/households/{householdId}/recurring-expenses/{recurringExpenseId}',
    tag: 'RecurringExpenses',
    summary: 'Delete a recurring expense',
    request: recurringExpenseIdParam,
    successStatus: 204,
    successDescription: 'Recurring expense soft-deleted',
  },

  // Attachments
  {
    method: 'post',
    path: '/households/{householdId}/expenses/{expenseId}/attachments',
    tag: 'Attachments',
    summary: 'Upload a receipt or invoice',
    multipart: true,
    request: attachmentsExpenseIdParam,
    successStatus: 201,
    successDescription: 'Attachment uploaded; mime type sniffed from content',
  },
  {
    method: 'get',
    path: '/households/{householdId}/expenses/{expenseId}/attachments',
    tag: 'Attachments',
    summary: 'List attachments for an expense',
    request: attachmentsExpenseIdParam,
    successStatus: 200,
    successDescription: 'Attachments',
  },
  {
    method: 'get',
    path: '/households/{householdId}/expenses/{expenseId}/attachments/{attachmentId}/download',
    tag: 'Attachments',
    summary: 'Get a short-lived download URL for an attachment',
    request: attachmentIdParam,
    successStatus: 200,
    successDescription: 'Presigned URL, valid for 5 minutes',
  },
  {
    method: 'delete',
    path: '/households/{householdId}/expenses/{expenseId}/attachments/{attachmentId}',
    tag: 'Attachments',
    summary: 'Delete an attachment',
    request: attachmentIdParam,
    successStatus: 204,
    successDescription: 'Attachment deleted',
  },

  // Analytics
  {
    method: 'get',
    path: '/households/{householdId}/analytics/summary',
    tag: 'Analytics',
    summary: 'Get total spent, total income and net for a date range',
    request: dateRangeSchema,
    successStatus: 200,
    successDescription: 'Summary for the range',
  },
  {
    method: 'get',
    path: '/households/{householdId}/analytics/by-category',
    tag: 'Analytics',
    summary: 'Get spend by category for a date range',
    request: dateRangeSchema,
    successStatus: 200,
    successDescription: 'Spend broken down by category',
  },
  {
    method: 'get',
    path: '/households/{householdId}/analytics/by-member',
    tag: 'Analytics',
    summary: "Get spend by member's split share for a date range",
    request: dateRangeSchema,
    successStatus: 200,
    successDescription: 'Spend broken down by member',
  },
  {
    method: 'get',
    path: '/households/{householdId}/analytics/over-time',
    tag: 'Analytics',
    summary: 'Get a spend time series for a date range',
    request: overTimeSchema,
    successStatus: 200,
    successDescription: 'Time series bucketed by day, week or month',
  },
  {
    method: 'get',
    path: '/households/{householdId}/analytics/comparison',
    tag: 'Analytics',
    summary: 'Compare a date range against the equal-length prior period',
    request: dateRangeSchema,
    successStatus: 200,
    successDescription: 'Current vs. previous period',
  },

  // Currencies
  {
    method: 'get',
    path: '/currencies',
    tag: 'Currencies',
    summary: 'List supported currencies',
    auth: false,
    successStatus: 200,
    successDescription: 'Currency catalog',
  },
];

export const openApiDocument = buildOpenApiDocument(routes);
