/**
 * Stable, documented catalog of application error codes. This is the
 * contract with API clients — see README.md § Catálogo de errores. Adding a
 * code here and using it via the `AppError` subclasses in errors.ts is the
 * only way a module should produce a domain error.
 */
export const ErrorCode = {
  // Generic (errors.ts base classes)
  BAD_REQUEST: 'BAD_REQUEST',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  INTERNAL_ERROR: 'INTERNAL_ERROR',

  // Auth
  TOKEN_REUSE_DETECTED: 'TOKEN_REUSE_DETECTED',
  EMAIL_ALREADY_REGISTERED: 'EMAIL_ALREADY_REGISTERED',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',

  // Households
  HOUSEHOLD_NOT_FOUND: 'HOUSEHOLD_NOT_FOUND',
  NOT_A_MEMBER: 'NOT_A_MEMBER',
  INSUFFICIENT_ROLE: 'INSUFFICIENT_ROLE',
  LAST_ADMIN: 'LAST_ADMIN',
  MEMBER_HAS_OPEN_BALANCE: 'MEMBER_HAS_OPEN_BALANCE',

  // Invitations
  INVITATION_NOT_FOUND: 'INVITATION_NOT_FOUND',
  INVITATION_EXPIRED: 'INVITATION_EXPIRED',
  INVITATION_ALREADY_RESOLVED: 'INVITATION_ALREADY_RESOLVED',
  INVITATION_ALREADY_PENDING: 'INVITATION_ALREADY_PENDING',
  ALREADY_MEMBER: 'ALREADY_MEMBER',

  // Expenses
  INVALID_PAYER: 'INVALID_PAYER',
  INVALID_PARTICIPANT: 'INVALID_PARTICIPANT',
  INVALID_EXPENSE_SPLIT: 'INVALID_EXPENSE_SPLIT',
  INVALID_CATEGORY: 'INVALID_CATEGORY',
  INVALID_CURRENCY: 'INVALID_CURRENCY',
  EXPENSE_ALREADY_VOIDED: 'EXPENSE_ALREADY_VOIDED',

  // Settlements
  INVALID_SETTLEMENT: 'INVALID_SETTLEMENT',
  SETTLEMENT_ALREADY_VOIDED: 'SETTLEMENT_ALREADY_VOIDED',

  // Recurring expenses
  RECURRING_OCCURRENCE_NOT_PENDING: 'RECURRING_OCCURRENCE_NOT_PENDING',

  // Attachments
  ATTACHMENT_TOO_LARGE: 'ATTACHMENT_TOO_LARGE',
  UNSUPPORTED_MEDIA_TYPE: 'UNSUPPORTED_MEDIA_TYPE',

  // Cross-cutting
  IDEMPOTENCY_KEY_CONFLICT: 'IDEMPOTENCY_KEY_CONFLICT',
  RATE_LIMITED: 'RATE_LIMITED',
} as const;

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];
